version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db 
    command: --quiet
    environment:
      - MONGO_INITDB_DATABASE=news_db
